import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainMenu from "@/components/MainMenu";
import SiteContextProvider from "@/components/SiteContextProvider";
import { userCheckByToken } from "@/utils/src/checkUserByToken";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const user = await userCheckByToken()

  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <SiteContextProvider
        initialUser={user}
        >
          <div className="flex flex-row">
            <MainMenu/>
            {children}
          </div>
        </SiteContextProvider>
      </body>
    </html>
  );
}
